version: '3.8'

services:
  python-app:
    build: 
      context: ./backend-service
    command: pipenv run python -m uvicorn src.service:app --host 0.0.0.0
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - database
    environment:
      - DB_URL=postgresql://postgres:Ie9yaAlhhb@database:5432/ionos

  database:
    build: 
      context: ./postgres
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
      - ./postgres/vehicle_table.sql:/docker-entrypoint-initdb.d/vehicle_table.sql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: Ie9yaAlhhb
      POSTGRES_DB: ionos

volumes:
  postgres_data:
